//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvisorManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CP25Team09Entities : DbContext
    {
        public CP25Team09Entities()
            : base("name=CP25Team09Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountUser> AccountUser { get; set; }
        public virtual DbSet<Advisor> Advisor { get; set; }
        public virtual DbSet<ListStudents> ListStudents { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<PlanAdvisor> PlanAdvisor { get; set; }
        public virtual DbSet<ProofPlan> ProofPlan { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleMenu> RoleMenu { get; set; }
        public virtual DbSet<Semester> Semester { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentStatus> StudentStatus { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VLClass> VLClass { get; set; }
        public virtual DbSet<PlanClass> PlanClass { get; set; }
    }
}
