//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvisorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationAdvisor
    {
        public int id { get; set; }
        public string rank_type { get; set; }
        public string rank_des { get; set; }
        public string description { get; set; }
        public Nullable<int> rank_count { get; set; }
        public Nullable<int> rank_end { get; set; }
    }
}
