//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvisorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanAdvisor
    {
        public int id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> number_title { get; set; }
        public string content { get; set; }
        public string hk1 { get; set; }
        public string hk2 { get; set; }
        public string hk3 { get; set; }
        public string describe { get; set; }
        public string source { get; set; }
        public string note { get; set; }
    }
}
