//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvisorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanStatus
    {
        public int id { get; set; }
        public Nullable<int> id_class { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public string message { get; set; }
        public string eval_advisor { get; set; }
        public string eval_admin { get; set; }
    }
}
