//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvisorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProofPlan
    {
        public int id { get; set; }
        public string content { get; set; }
        public string file_proof { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string semester { get; set; }
        public string status { get; set; }
        public Nullable<int> id_creator { get; set; }
        public Nullable<int> id_browser { get; set; }
        public Nullable<int> id_titleplan { get; set; }
    }
}
