//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvisorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string studentcode { get; set; }
        public string id_Class { get; set; }
        public string trainningPoint { get; set; }
        public string gradePointAverage { get; set; }
        public Nullable<int> id_Status { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
